version: '3.4'

services:
  etcd:
    image: docker.io/bitnami/etcd:latest
    hostname: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - '2379:2379'
    volumes:
      - etcd_data:/bitnami/etcd

volumes:
  etcd_data:
    driver: local